### PR TITLE
fix for version 16.2.5

### PR DESCRIPTION
**Pull request by abela-a**
original source code from @lyc8503 in issue #4

### CODE REVIEW

**Comment by Aithosa** [comment]
可以加个NavicatDataModeler的脚本吗 T.T

**Comment by abela-a** [comment]
> 可以加个NavicatDataModeler的脚本吗 T.T

i'm sorry, i don't know :(

**Review by otis-vinova — CHANGES_REQUESTED** [review]
It's working

**Review by LeninElio — COMMENTED** [review]
Working... Navicat 16.3.0

**Comment by Danydeidei** [comment]
Hi, I used your code on previous Navicat Premium versione and it works.
With the last Navicat Premium (16.3.2) and Navicat for Postgres (16.3.2) is not working
WIN 11

**Comment by abela-a** [comment]
> Hi, I used your code on previous Navicat Premium versione and it works.
> With the last Navicat Premium (16.3.2) and Navicat for Postgres (16.3.2) is not working
> WIN 11

sorry. for now, just downgrade your navicat

**Comment by lyc8503** [comment]
> Hi, I used your code on previous Navicat Premium versione and it works. With the last Navicat Premium (16.3.2) and Navicat for Postgres (16.3.2) is not working WIN 11

Any new features on 16.3.2? I personally wrote the bat script for 16.2.x as they added integrated support for redis and that's useful to me. I may not keep on upgrading this if there're no new features I needed. Sorry.

**Pull request closed without merging**
